### ISSUE TITLE
project doesn't work on mac

### ISSUE THREAD

**Issue by ahmedre** [khalid-hussain/MatnAjrumiyyah#7]
you have a package named Model with a capital M - this makes android studio on mac not able to pick up the files in it. instead, i had to rename it twice (once to anything else, then back to model lower case so that it works). i am guessing you'll have to do this over two commits - one in github to rename to something else, and then another one to name back to models, but with a lowercase m.

**Comment by khalid-hussain** [comment]
Should be fixed now. Thanks for the heads up.
